name: ${plugin}
version: ${project.version}
main: ${package}
author: "Felux"
softdepend: ["WorldGuard"]
website: https://felux.io/

commands:
  pouches:
    aliases: ["pouch"]
    description: "The main plugin command."